version: '3'
services:
    nodets_app:
        build: .
        command: npm run dev
        ports:
            - "3333:3333"
        volumes:
            - .:/usr/app
        networks: 
            - default

    nodets_auth_db:
        image: mysql:5.7.29
        container_name: nodets_auth_db
        restart: unless-stopped
        tty: true
        ports: 
        - "3306:3306"
        environment: 
            MYSQL_DATABASE: nodets_auth
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks: 
            - default
        volumes: 
            - ./docker/mysql:/var/lib/mysql
            

networks:
    default:
        driver: bridge